### ISSUE TITLE
fofa接口无效

### ISSUE THREAD

**Issue by len0m0** [ZhuriLab/Starmap#4]
师傅fofajiekou好像没用，添加api后也是。

**Comment by yhy0** [comment]
可以啊, ./Starmap -d baidu.com -s fofa -v 指定看看有啥报错， 我这边是正常的，你可能用的老版本，之前 fofo 换接口了，换到了 fofo.info

**Comment by len0m0** [comment]
![image](https://user-images.githubusercontent.com/66287939/177929703-1788bcb1-8646-4ef0-a0f1-652eced61f58.png)
![image](https://user-images.githubusercontent.com/66287939/177929800-1b951967-eccf-4260-bf81-85b823b13e50.png)
使用没报错，不过所有域名永fofa都是0

**Comment by yhy0** [comment]
fofa 的配置 同时需要邮箱和key， 格式为 邮箱:key

**Comment by len0m0** [comment]
谢谢
